name: いかそばの部屋
description: ここはいかそばの...、なんだっけ
markdown: kramdown
timezone: japan/tokyo
lang: ja
permalink: /:categories/:year/:month/:day/:title:output_ext
url: 192.168.0.4:4000
kramdown:
  syntax_highlighter: rouge