name: いかそばの部屋
description: ここはいかそばの...、なんだっけ
markdown: kramdown
timezone: japan/tokyo
lang: ja
permalink: /:categories/:year/:month/:day/:title:output_ext
url: https://ikasoba.github.io
domain: ikasoba.github.io
kramdown:
  syntax_highlighter: rouge